# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('hand', models.CharField(max_length=32)),
                ('summ', models.IntegerField()),
                ('cards', models.CharField(max_length=32)),
                ('action', models.CharField(max_length=32)),
                ('rate', models.FloatField()),
                ('win', models.FloatField()),
            ],
            options={
                'db_table': 'description',
                'verbose_name_plural': 'description',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('wagered', models.FloatField()),
                ('result', models.FloatField()),
                ('identifier', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'detail',
                'verbose_name_plural': 'detail',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('game', models.CharField(max_length=32)),
                ('min', models.IntegerField()),
                ('plays', models.IntegerField()),
                ('wagered', models.FloatField()),
                ('winnings', models.FloatField()),
                ('pending', models.FloatField()),
                ('identifier', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'summary',
                'verbose_name_plural': 'summary',
            },
        ),
        migrations.AddField(
            model_name='detail',
            name='summary_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.Summary'),
        ),
        migrations.AddField(
            model_name='description',
            name='detail_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.Detail'),
        ),
    ]
